format_version: v1.0
type: UniqueComponent
attributes: {id: rstc}
children:
- type: Symbols
  children:
  - type: Float
    attributes: {id: RSTC_EXTERNAL_RESET_LENGTH_MSECS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rstc, value: '0.063'}
  - type: KeyValueSet
    attributes: {id: RSTC_MR_EXTERNAL_RESET_ACTION}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rstc, value: '0'}
- type: ElementPosition
  attributes: {x: '440', y: '20', id: rstc}
