format_version: v1.0
type: UniqueComponent
attributes: {id: tc0}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TC2_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '200000000'}
  - type: Combo
    attributes: {id: TC2_CMR_BCPB}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: CLEAR}
  - type: Combo
    attributes: {id: TC2_CMR_BCPC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SET}
  - type: Menu
    attributes: {id: TC2_COMPARE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Long
    attributes: {id: TC2_COMPARE_A}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '200000'}
    - type: Values
      children:
      - type: User
        attributes: {value: '100000'}
  - type: Long
    attributes: {id: TC2_COMPARE_B}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '200000'}
    - type: Values
      children:
      - type: User
        attributes: {value: '100000'}
  - type: Boolean
    attributes: {id: TC2_COMPARE_IER_CPCS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Comment
    attributes: {id: TC2_COMPARE_PERIOD}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Waveform Period is 1000.0 uS****'}
  - type: Long
    attributes: {id: TC2_COMPARE_PERIOD_COUNT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '200000'}
  - type: Boolean
    attributes: {id: TC2_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Combo
    attributes: {id: TC2_OPERATING_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: COMPARE}
  - type: Comment
    attributes: {id: TC2_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Clock resolution is 5.0 nS****'}
  - type: Menu
    attributes: {id: TC2_TIMER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Comment
    attributes: {id: TC2_TIMER_PERIOD_CMT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Period Count is 80000****'}
  - type: Long
    attributes: {id: TC2_TIMER_PERIOD_COUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '80000'}
  - type: Integer
    attributes: {id: TC3_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '200000000'}
  - type: Boolean
    attributes: {id: TC3_PCK7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'false'}
- type: ElementPosition
  attributes: {x: '440', y: '20', id: tc0}
