format_version: v1.0
type: UniqueComponent
attributes: {id: pit64b0}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: CONT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_INTERRUPT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pit64b0, value: 'false'}
  - type: Long
    attributes: {id: PERIOD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '42949672960'}
  - type: Long
    attributes: {id: PERIOD_LSB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pit64b0, value: '0'}
  - type: Integer
    attributes: {id: PERIOD_MSB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pit64b0, value: '10'}
  - type: Float
    attributes: {id: PERIOD_US}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pit64b0, value: '2.14748368E8'}
  - type: Integer
    attributes: {id: SRC_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pit64b0, value: '200000000'}
- type: ElementPosition
  attributes: {x: '440', y: '22', id: pit64b0}
