format_version: v1.0
type: UniqueComponent
attributes: {id: acc}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: ACC_INPUT_SELPLUS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: KeyValueSet
    attributes: {id: ACC_INTERRUPT_EDGETYPE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Boolean
    attributes: {id: ACC_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '440', y: '20', id: acc}
