configName: sam_a7g5_ek
folderName: sam_a7g5_ek
format_version: v1.0
frameworkPath: ../../../..
processor: SAMA7G54
projectName: dwdt_timeout_sam_a7g5_ek
settings:
  PackageFilter: bsp;core;csp;Devices;dev_packs;harmony-services;quick_docs
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\SAMA7G5_DFP\1.0.52\atdf\SAMA7G54.atdf
