format_version: v1.0
type: UniqueComponent
attributes: {id: tc0}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TC0_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '200000000'}
  - type: Boolean
    attributes: {id: TC0_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Comment
    attributes: {id: TC0_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Clock resolution is 5.0 nS****'}
  - type: Comment
    attributes: {id: TC0_TIMER_PERIOD_CMT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Period Count is 100000000****'}
  - type: Long
    attributes: {id: TC0_TIMER_PERIOD_COUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '100000000'}
  - type: Float
    attributes: {id: TC0_TIMER_PERIOD_MS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '500.0'}
  - type: Integer
    attributes: {id: TC3_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '200000000'}
  - type: Boolean
    attributes: {id: TC3_PCK7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'false'}
  - type: Comment
    attributes: {id: TC_QEI_PERIOD_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Time Base is 75.075 uS****'}
- type: ElementPosition
  attributes: {x: '440', y: '20', id: tc0}
