format_version: v1.0
type: UniqueComponent
attributes: {id: shdwc}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: EVENT_LIST}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: shdwc, value: ' RTCWKEN'}
  - type: Boolean
    attributes: {id: RTCWKEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '580', y: '20', id: shdwc}
