format_version: v1.0
type: UniqueComponent
attributes: {id: qspi0}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: QSPISPI_HEADER2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: QSPISPI_SOURCE2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: QSPI_CLK_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** QSPI0 Core Clock Frequency Is Set To 133.333333
            MHz'}
  - type: Integer
    attributes: {id: QSPI_CLK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi0, value: '133333333'}
  - type: KeyValueSet
    attributes: {id: QSPI_CPOL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi0, value: '0'}
  - type: Boolean
    attributes: {id: QSPI_DLLCFG_RANGE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi0, value: 'true'}
  - type: File
    attributes: {id: QSPI_HEADER2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: QSPI_NBBITS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: QSPI_SMM}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: File
    attributes: {id: QSPI_SOURCE1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Hex
    attributes: {id: SPI_DUMMY_DATA}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '255'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi0, value: '255'}
- type: ElementPosition
  attributes: {x: '440', y: '20', id: qspi0}
