configName: sam_a7g5_ek
folderName: sam_a7g5_ek
format_version: v1.0
frameworkPath: ..\..\..\..\..\framework
processor: SAMA7G54
projectName: start_stop_period_change_sam_a7g5_ek
settings:
  PackageFilter: bsp;core;csp;touch
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMA7G5_DFP\1.0.30\atdf\SAMA7G54.atdf
